import Link from "next/link";
import { TrackedLink } from "@/components/tracked-link";
import { breadcrumbJsonLd } from "@/lib/jsonld";

const sourcePage = "banh-xeo-hoi-an";

const images = {
  hero: "/images/editorial/food-guide/banh-xeo.webp",
  setup: "/images/editorial/banh-xeo/serving-setup.webp",
  pan: "/images/editorial/banh-xeo/pan-cooking.webp",
  dipping: "/images/editorial/banh-xeo/wrap-dipping.webp",
} as const;

function BanhXeoImage({ src, alt, priority = false }: { src: string; alt: string; priority?: boolean }) {
  return <figure className="banh-xeo-visual"><img src={src} alt={alt} width="1200" height="800" loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"} decoding="async" /></figure>;
}

export function BanhXeoGuidePage() {
  const breadcrumb = breadcrumbJsonLd([
    { name: "Home", url: "https://hoianlocaldays.com" },
    { name: "Hoi An Food Guide", url: "https://hoianlocaldays.com/hoi-an-food-guide" },
    { name: "Banh Xeo in Hoi An", url: "https://hoianlocaldays.com/banh-xeo-hoi-an" },
  ]);

  return <main className="banh-xeo-guide-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
    <div className="breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/hoi-an-food-guide">Food Guide</Link><span>›</span><span>Banh Xeo</span></div>

    <section className="banh-xeo-hero section"><div><p className="eyebrow">A practical first-timer guide · Reviewed August 2026</p><h1>Banh Xeo in Hoi An: What It Is &amp; How to Eat It</h1><p>Hoi An-style banh xeo is a small, crisp savory pancake best understood as a wrap: break off a hot piece, add herbs and vegetables, roll it in rice paper when provided, then dip it in the accompanying sauce.</p><nav className="quick-nav" aria-label="On this page"><a href="#quick-answer">Quick answer</a><a href="#how-to-eat">How to eat</a><a href="#regional-style">Compare styles</a><a href="#dietary">Dietary needs</a></nav></div><BanhXeoImage src={images.hero} alt="Editorial illustration of small crisp banh xeo served with rice paper, herbs and dipping sauce" priority /></section>

    <section className="banh-xeo-quick section" id="quick-answer"><div><p className="eyebrow">Quick answer</p><h2>What Should You Expect?</h2></div><dl><div><dt>Format</dt><dd>A small, hot fried pancake that you break into manageable pieces.</dd></div><div><dt>Texture</dt><dd>Crisp pancake balanced by fresh herbs, vegetables and wrapper.</dd></div><div><dt>Filling</dt><dd>Shrimp, pork and bean sprouts are common, but vendors vary.</dd></div><div><dt>Sauce</dt><dd>Fish-sauce-based, thicker peanut or house sauces may appear.</dd></div><div><dt>Best moment</dt><dd>Soon after cooking, while the shell is still hot and crisp.</dd></div></dl></section>

    <section className="banh-xeo-intro section"><div><p className="eyebrow">The dish</p><h2>What Is Banh Xeo?</h2></div><div><p>Banh xeo is a savory Vietnamese pancake made by pouring a thin batter into a hot, oiled pan with fillings such as shrimp, pork and bean sprouts. The batter sets around the ingredients and develops a crisp edge before the pancake is folded.</p><p>Rice flour is a common base. Turmeric is commonly used for yellow color, but batter formulas vary; coconut milk is present in some recipes and regional styles, not a universal Hoi An requirement. The Hoi An heritage portal also describes local batter using rice flour and soybean, showing why one nationwide recipe should not be assumed.</p><aside><strong>Why “xeo”?</strong> Official local heritage material explains the name as an onomatopoeic reference to the sizzling sound when batter hits the hot pan.</aside></div></section>

    <section className="banh-xeo-style section"><BanhXeoImage src={images.pan} alt="Temporary editorial illustration of a small banh xeo cooking until crisp in a hot pan" /><div><p className="eyebrow">A broad regional tendency</p><h2>What Makes Hoi An-Style Banh Xeo Different?</h2><p>Official Hoi An sources describe Central and Hoi An pancakes as smaller than the large southern format. The compact size makes it easier to cook several crisp pancakes and divide each one into pieces for wrapping.</p><p>Hoi An servings often emphasize shrimp, bean sprouts and thin pork, followed by herbs, greens, rice paper and dipping sauce. That is a useful local pattern, not a fixed definition: fillings, batter, wrapper, vegetables and sauces change between cooks.</p><p>The practical difference for a visitor is scale and eating style. Do not expect one large pancake to be placed in front of you as a complete, self-contained plate.</p></div></section>

    <section className="banh-xeo-inside section"><div><p className="eyebrow">Read the serving</p><h2>What&apos;s Inside Banh Xeo?</h2></div><div className="banh-xeo-parts"><article><span>01</span><h3>The batter</h3><p>Commonly rice-flour based, spread thinly in a hot oiled pan. Turmeric, coconut milk, soybean, spring onion or other additions depend on the cook and region.</p></article><article><span>02</span><h3>The filling</h3><p>Shrimp, thin pork and bean sprouts are common Hoi An descriptions. Mung bean, onion and other vegetables may also appear.</p></article><article><span>03</span><h3>The fresh side</h3><p>Herbs, lettuce, greens and cucumber where served cool and lighten the fried pancake.</p></article><article><span>04</span><h3>The wrapper</h3><p>Dry rice paper commonly turns the components into a hand-held roll. Some places may use leaves or a different wrapper setup.</p></article><article><span>05</span><h3>The sauce</h3><p>The sauce connects the crisp, savory and fresh components. Its ingredients and thickness can change the whole experience.</p></article></div></section>

    <section className="banh-xeo-balance section"><div><p className="eyebrow">Information visitors often miss</p><h2>Why the Herbs, Wrapper &amp; Sauce Matter</h2></div><div><p>Eating only the fried pancake gives you the richest and heaviest part of the dish. The complete serving is designed around contrast: crisp and warm pancake, cool herbs and vegetables, a flexible wrapper, savory filling and a measured amount of sauce.</p><p>The herbs are not decorative. The wrapper is not just packaging. Together they control the ratio of fried food to fresh ingredients and make each bite easier to manage.</p><aside><strong>Build a small roll first.</strong> Overfilling makes it harder to hold and can hide the pancake&apos;s crisp texture.</aside></div></section>

    <section className="banh-xeo-eating section" id="how-to-eat"><BanhXeoImage src={images.setup} alt="Temporary editorial illustration of banh xeo with separate rice paper, fresh herbs, cucumber and sauce" /><div><p className="eyebrow">A practical sequence, not etiquette</p><h2>How to Eat Banh Xeo</h2><ol><li><span>1</span><div><h3>Take a wrapper if provided</h3><p>Use one sheet of rice paper or the wrapper the restaurant serves.</p></div></li><li><span>2</span><div><h3>Add herbs and vegetables</h3><p>Start with a modest amount of greens and cucumber where available.</p></div></li><li><span>3</span><div><h3>Add a manageable piece</h3><p>Break or cut the hot pancake so the roll can close without crushing everything.</p></div></li><li><span>4</span><div><h3>Roll it together</h3><p>Fold firmly enough to hold the components, without worrying about a perfect shape.</p></div></li><li><span>5</span><div><h3>Dip lightly and taste</h3><p>Try the house sauce before adding chili or other condiments.</p></div></li></ol></div></section>

    <section className="banh-xeo-sauce section"><div><p className="eyebrow">The sauce is not universal</p><h2>What Dipping Sauce Comes With It?</h2></div><div><p>You may receive a light fish-sauce-based dip, a thicker sauce involving soybean or peanuts, or a house-specific preparation. Official Hoi An sources themselves describe more than one style, including sweet-sour fish sauce and thicker soybean-peanut sauce.</p><p>That variation matters for taste and dietary needs. A thicker sauce may feel richer and nuttier; a lighter sauce may emphasize acidity, sweetness, chili and fish sauce. Neither should be declared the only “authentic” Hoi An option.</p><ul><li>Taste before adding extra chili or condiments.</li><li>Ask about fish sauce, peanuts, soybean and wheat-containing seasonings when relevant.</li><li>Do not assume a vegetarian pancake automatically comes with vegetarian sauce.</li></ul></div></section>

    <section className="banh-xeo-compare section" id="regional-style"><div><p className="eyebrow">Broad tendencies, not rigid categories</p><h2>Hoi An Banh Xeo vs Southern Banh Xeo</h2></div><div className="banh-xeo-table-scroll" role="region" aria-label="Hoi An and Southern banh xeo comparison" tabIndex={0}><table><thead><tr><th>Feature</th><th>Hoi An / Central tendency</th><th>Southern tendency</th></tr></thead><tbody><tr><th scope="row">Size</th><td>Generally smaller and easier to divide into wraps</td><td>Often much larger, particularly in the Mekong Delta</td></tr><tr><th scope="row">Serving impression</th><td>Several compact pancakes may form the meal</td><td>One large pancake may dominate the plate</td></tr><tr><th scope="row">Common fillings</th><td>Shrimp, bean sprouts and thin pork are common descriptions</td><td>Pork, shrimp and bean sprouts are also common, often in a fuller pancake</td></tr><tr><th scope="row">Batter</th><td>Rice-based local formulas vary; coconut milk is not assumed</td><td>Coconut milk is common in many southern recipes, but not universal</td></tr><tr><th scope="row">How it is eaten</th><td>Rice paper, herbs, vegetables and dipping sauce are commonly served</td><td>Often wrapped in lettuce or greens with herbs and nuoc cham</td></tr></tbody></table></div><p className="banh-xeo-note">Vietnam has many local versions beyond these two broad patterns. Individual kitchens may cross the tendencies shown here.</p></section>

    <section className="banh-xeo-dietary section" id="dietary"><div><p className="eyebrow">Confirm the whole serving</p><h2>Is Banh Xeo Vegetarian or Gluten-Free?</h2></div><div><p>Common Hoi An-style versions may contain shrimp, pork and animal-based dipping sauce. Vegetarian and vegan adaptations exist, but the filling, batter and sauce all need confirmation.</p><p>Rice flour is common, yet the finished dish should not automatically be called gluten-free. Batter mixes, seasoning, soy sauce, dipping sauce, shared pans, utensils, oil and preparation surfaces can introduce wheat or cross-contact.</p><ul><li><strong>Coeliac disease or wheat allergy:</strong> ask about the batter mix, seasonings, sauce and shared cooking equipment.</li><li><strong>Seafood allergy:</strong> shrimp is common and the same pan or utensils may be used across orders.</li><li><strong>Peanut or soy allergy:</strong> thicker dipping sauces require specific checking.</li><li><strong>Vegetarian or vegan:</strong> verify batter, filling, cooking fat and dipping sauce separately.</li></ul><p>HAL cannot verify individual kitchens or guarantee an allergy-safe preparation.</p></div></section>

    <section className="banh-xeo-timing section"><BanhXeoImage src={images.dipping} alt="Temporary editorial illustration of a banh xeo, herb and cucumber roll being dipped into sauce" /><div><p className="eyebrow">Timing protects the texture</p><h2>When Is Banh Xeo Best?</h2><p>Eat it soon after it leaves the pan. Steam from the filling and time on the plate gradually soften the shell, reducing the contrast that makes the wrapped bite work.</p><p>Hoi An heritage material associates hot banh xeo with cooler and rainy weather, and owner observation agrees that this is an especially enjoyable context. Treat that as local food culture and seasonal atmosphere—not a rule or a guaranteed “best season.”</p><aside><strong>Do not wait for the whole table.</strong> If everyone is comfortable, begin assembling while the first pancake is still crisp.</aside></div></section>

    <section className="banh-xeo-choice section"><div><p className="eyebrow">Decision support</p><h2>Banh Xeo vs Cao Lau</h2></div><div className="banh-xeo-choice-grid"><article><h3>Choose Cao Lau when you want…</h3><ul><li>A bowl-style meal strongly associated with Hoi An</li><li>Thick, chewy noodles</li><li>A small amount of concentrated sauce</li><li>A less hands-on eating format</li></ul><Link href="/cao-lau-hoi-an">Understand Cao Lau →</Link></article><article><h3>Choose Banh Xeo when you want…</h3><ul><li>A hot, crisp pancake</li><li>Herbs and fresh vegetables in each bite</li><li>Wrapping and dipping</li><li>A more interactive shared meal</li></ul><p>If your first visit includes enough meals, try both rather than choosing a winner.</p></article></div></section>

    <section className="banh-xeo-worth section"><div><p className="eyebrow">The HAL view</p><h2>Is Banh Xeo Worth Trying?</h2></div><div><p>Yes for most first-time visitors. It shows how Vietnamese meals often depend on assembly and balance rather than one centerpiece: fried food becomes lighter and more interesting when combined with herbs, wrapper and dipping sauce.</p><p>It may be less suitable if you dislike fried foods, need common allergens controlled without clear kitchen communication, or want an extremely quick grab-and-go meal. The wrapping takes a little attention, and that is part of its appeal.</p></div></section>

    <section className="banh-xeo-learning section"><div><p className="eyebrow">Technique becomes visible</p><h2>Want to Learn How It&apos;s Made?</h2></div><div><p>A cooking class can make batter consistency, pan heat, crisping, filling, wrapping and dipping sauce easier to understand. Check the actual class menu first: banh xeo is not included in every program.</p><TrackedLink className="primary-button" href="/cooking-classes-hoi-an" sourcePage={sourcePage} destinationPage="/cooking-classes-hoi-an" section="cooking_bridge" ctaId="banh_xeo_cooking_classes">Compare Hoi An Cooking Classes</TrackedLink></div></section>

    <section className="banh-xeo-bridge section"><div><p className="eyebrow">Explore more Hoi An food</p><h2>Place the Dish in Your Trip</h2></div><nav><Link href="/hoi-an-food-guide"><span>What else to eat</span><strong>Hoi An Food Guide</strong></Link><Link href="/hoi-an-market-guide"><span>Understand ingredients</span><strong>Hoi An Market Guide</strong></Link><Link href="/3-days-in-hoi-an"><span>Plan meal timing</span><strong>3 Days in Hoi An</strong></Link><Link href="/editorial-methodology"><span>How we check claims</span><strong>Editorial Methodology</strong></Link></nav></section>

    <section className="banh-xeo-sources section"><div><p className="eyebrow">How this guide was checked</p><h2>Sources &amp; Editorial Caution</h2></div><div><p>Local format, batter descriptions, sizzling-name context and rainy-weather association were checked against the <a href="https://www.hoianworldheritage.org.vn/en/news/Traditionnal-Hoi-An-food/Banh-Xeo-54.hwh" target="_blank" rel="noopener noreferrer">Hoi An heritage portal</a> and its <a href="https://www.hoianworldheritage.org.vn/vi/news/am-thuc-hoi-an/Banh-xeo-Hoi-An-100.hwh" target="_blank" rel="noopener noreferrer">Vietnamese local feature</a>. Eating format was cross-checked with <a href="https://www.vietnam.travel/things-to-do/vietnamese-home-recipes" target="_blank" rel="noopener noreferrer">Vietnam Tourism</a>. Southern scale was compared with its <a href="https://www.vietnam.travel/things-to-do/dining-mekong-delta" target="_blank" rel="noopener noreferrer">Mekong Delta guide</a>.</p><p>Where recipes and sauces differ, HAL describes tendencies rather than declaring one universal formula.</p></div></section>
  </main>;
}
