import Link from "next/link";
import { basketBoatDecisionTypes, basketBoatMistakes, basketBoatTypes } from "@/data/basket-boat";
import { breadcrumbJsonLd } from "@/lib/jsonld";

export function BasketBoatPage() {
  const breadcrumb = breadcrumbJsonLd([{ name: "Home", url: "https://hoianlocaldays.com" }, { name: "Things to Do in Hoi An", url: "https://hoianlocaldays.com/things-to-do-in-hoi-an" }, { name: "Basket Boat Experiences", url: "https://hoianlocaldays.com/basket-boat-hoi-an" }]);
  return <main className="basket-hub">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
    <div className="breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/things-to-do-in-hoi-an">Things to Do</Link><span>›</span><span>Basket Boats</span></div>
    <section className="basket-hero section"><p className="eyebrow">Independent local decision guide</p><h1>Best Basket Boat Experiences in Hoi An</h1><p>A practical guide to choosing a coconut basket boat experience — from short rides to market, cooking and countryside combinations.</p><aside>Not all basket boat experiences are the same. The right choice depends on whether you want a quick ride, a quieter experience or a half-day combination tour.</aside></section>
    <section className="basket-decisions section"><div className="basket-heading"><p className="eyebrow">Choose the format first</p><h2>Which Basket Boat Experience Is Right for You?</h2></div><div className="basket-decision-grid">{basketBoatDecisionTypes.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><strong>{item.recommendation}</strong><p>{item.guidance}</p>{item.href && item.cta ? <Link href={item.href}>{item.cta} →</Link> : null}</article>)}</div></section>
    <section className="basket-explainer section"><div><p className="eyebrow">The basic experience</p><h2>What Is the Hoi An Basket Boat Experience?</h2></div><div><p>Basket boats are round bamboo boats used on coconut-lined waterways commonly associated with the Cam Thanh area. The ride format varies significantly by operator.</p><p>Some experiences are lively and entertainment-focused; others emphasize scenery or local context. Many tours combine the ride with cooking, a market visit or other activities.</p></div></section>
    <section className="basket-types section"><div className="basket-heading inverse"><p className="eyebrow">Compare the main formats</p><h2>The Main Types of Basket Boat Experiences</h2></div><div className="basket-type-grid">{basketBoatTypes.map((item) => <article key={item.title}><h3>{item.title}</h3><strong>Best for</strong><ul>{item.bestFor.map((point) => <li key={point}>{point}</li>)}</ul><small><b>Trade-off:</b> {item.tradeOff}</small>{item.href ? <Link href={item.href}>Compare Cooking Classes →</Link> : null}</article>)}</div></section>
    <section className="basket-atmosphere section"><div><p className="eyebrow">The most important trade-off</p><h2>Fun &amp; Lively or Quiet &amp; Scenic?</h2><p>Some basket boat experiences may include music, boat spinning, performances and busy waterways. Other formats place more emphasis on the setting and a calmer pace. Neither style is objectively better.</p></div><div className="atmosphere-choices"><article><h3>Fun &amp; Lively</h3><p>May suit groups, energetic travelers and families with children who enjoy active entertainment.</p></article><article><h3>Quiet &amp; Scenic</h3><p>May suit travelers seeking scenery, very young children sensitive to noise, or people who dislike highly touristic entertainment.</p></article></div></section>
    <section className="basket-family section"><div><p className="eyebrow">Balanced family guidance</p><h2>Are Basket Boats Good for Families?</h2><p>The experience is relatively short, visually interesting, easy to combine with other activities and memorable for many children.</p><Link className="primary-button" href="/hoi-an-with-kids">See Our Hoi An Family Guide</Link></div><aside><h3>Consider before choosing</h3><ul><li>Heat and waiting</li><li>Noise and busy waterways</li><li>Whether boat spinning is part of the format</li><li>Different children react differently</li></ul></aside></section>
    <section className="basket-combo section"><div className="basket-heading"><p className="eyebrow">A simple half-day decision</p><h2>Basket Boat Only or Combine It With Cooking?</h2></div><div className="combo-grid"><article><h3>Basket Boat Only</h3><p>Choose this if you are short on time, cooking does not interest you or you already have other plans.</p></article><article><h3>Basket Boat + Cooking</h3><p>Choose this for a first Hoi An trip, a family or couple experience, more value from a half-day, or an interest in food.</p><Link className="primary-button" href="/cooking-classes-hoi-an">Compare 7 Hoi An Cooking Experiences</Link></article></div></section>
    <section className="basket-practical section"><article><p className="eyebrow">Timing</p><h2>When Should You Go?</h2><p>Morning and afternoon can be easier than the midday heat. Weather and busier periods change the feel of the waterways, so confirm current conditions and keep some flexibility.</p></article><article><p className="eyebrow">A short checklist</p><h2>What to Bring</h2><ul><li>Water</li><li>Sun protection</li><li>Comfortable clothing</li><li>Footwear appropriate for getting in and out of boats</li><li>Phone or camera protection when appropriate</li></ul></article></section>
    <section className="basket-mistakes section"><div className="basket-heading inverse"><p className="eyebrow">Compare what is actually included</p><h2>Common Mistakes When Choosing a Basket Boat Tour</h2></div><div className="mistake-list">{basketBoatMistakes.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.guidance}</p>{item.href ? <Link href={item.href}>Check Cooking Class Combinations →</Link> : null}</div></article>)}</div></section>
    <section className="basket-method section"><div><p className="eyebrow">Our Basket Boat Picks</p><h2>Recommendations will be experience-led.</h2></div><div><p>When we publish specific picks, we will group matching provider listings under the same underlying experience and explain who each format suits. We will not rank an operator until its details are researched and verified.</p><nav aria-label="Continue planning"><Link href="/things-to-do-in-hoi-an">Explore Things to Do</Link><Link href="/cooking-classes-hoi-an">Compare Cooking Classes</Link><Link href="/hoi-an-with-kids">Plan With Kids</Link></nav></div></section>
  </main>;
}
