import Link from "next/link";
import { TrackedLink } from "@/components/tracked-link";
import { breadcrumbJsonLd } from "@/lib/jsonld";

const sourcePage = "cao-lau-hoi-an";

const images = {
  hero: "/images/editorial/food-guide/cao-lau.webp",
  detail: "/images/editorial/cao-lau/noodle-detail.webp",
  mixed: "/images/editorial/cao-lau/mixed-bowl.webp",
  ingredients: "/images/editorial/market-guide/ingredients.webp",
} as const;

function CaoLauImage({ src, alt, priority = false }: { src: string; alt: string; priority?: boolean }) {
  return <figure className="cao-visual"><img src={src} alt={alt} width="1200" height="800" loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"} decoding="async" /></figure>;
}

export function CaoLauGuidePage() {
  const breadcrumb = breadcrumbJsonLd([
    { name: "Home", url: "https://hoianlocaldays.com" },
    { name: "Hoi An Food Guide", url: "https://hoianlocaldays.com/hoi-an-food-guide" },
    { name: "Cao Lau in Hoi An", url: "https://hoianlocaldays.com/cao-lau-hoi-an" },
  ]);

  return <main className="cao-guide-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
    <div className="breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/hoi-an-food-guide">Food Guide</Link><span>›</span><span>Cao Lau</span></div>

    <section className="cao-hero section">
      <div><p className="eyebrow">A first-timer guide · Reviewed August 2026</p><h1>Cao Lau in Hoi An: What It Is &amp; How to Eat It</h1><p>Cao lau is Hoi An&apos;s defining noodle dish: thick, chewy noodles, char siu-style pork, fresh herbs, bean sprouts, crisp rice elements and only a small amount of concentrated sauce. It is not a bowl of noodle soup.</p><nav className="quick-nav" aria-label="On this page"><a href="#quick-answer">Quick answer</a><a href="#what-is-it">The bowl</a><a href="#cao-lau-vs-mi-quang">Compare</a><a href="#dietary">Dietary needs</a></nav></div>
      <CaoLauImage src={images.hero} alt="Editorial illustration of a cao lau-inspired bowl with thick noodles, pork, herbs and crisp elements" priority />
    </section>

    <section className="cao-quick section" id="quick-answer"><div><p className="eyebrow">Quick answer</p><h2>What Should You Expect?</h2></div><dl><div><dt>Texture</dt><dd>Chewy noodles, tender pork, fresh herbs and crisp toppings in one bite.</dd></div><div><dt>Liquid</dt><dd>A little concentrated sauce at the bottom—not a full bowl of broth.</dd></div><div><dt>How to eat it</dt><dd>Mix from the bottom before taking a full bite.</dd></div><div><dt>Flavor</dt><dd>Savory and gently sweet, balanced by herbs, sprouts and crunch.</dd></div><div><dt>Good first choice?</dt><dd>Yes, especially if you want one dish closely associated with Hoi An.</dd></div></dl></section>

    <section className="cao-intro section" id="what-is-it"><div><p className="eyebrow">The dish</p><h2>What Is Cao Lau?</h2></div><div><p>Cao lau is a dry-style noodle dish associated with Hoi An. A typical bowl combines thick rice-based noodles with sliced pork, fresh herbs, bean sprouts, crisp rice pieces and a small amount of rich sauce. Individual cooks vary the pork, herbs, sweetness, seasoning and crisp elements.</p><p>The bowl makes sense through contrast. The noodles provide chew; pork and sauce bring depth; herbs and sprouts keep it fresh; crisp pieces interrupt the softer textures. If you approach it expecting pho, the lack of broth may seem surprising. That is part of the design, not an omission.</p><aside><strong>The useful test is texture.</strong> A satisfying bowl should feel lively after mixing rather than wet, heavy or one-dimensional.</aside></div></section>

    <section className="cao-intro cao-broth section"><div><p className="eyebrow">Sauce, not soup</p><h2>Why Cao Lau Has So Little Broth</h2></div><div><p>The liquid in cao lau is intended to season and coat the noodles. It commonly comes from the seasoned pork and its cooking liquid, producing a concentrated savory-sweet layer rather than the large volume expected in pho.</p><p>Before judging the bowl as dry, mix it. A few turns bring the sauce up from the bottom and distribute it across the noodles. The low-liquid structure also helps the noodles retain their chew and the crisp elements remain distinct.</p></div></section>

    <section className="cao-components section"><CaoLauImage src={images.detail} alt="Temporary editorial illustration showing thick cao lau-style noodles, pork, herbs, sprouts and crisp rice pieces" /><div><p className="eyebrow">Read the bowl</p><h2>What Is in Cao Lau?</h2><ol><li><span>01</span><div><h3>Thick noodles</h3><p>Rice-based noodles with a notably firm, chewy texture. Their bite is one of the clearest differences from softer soup noodles.</p></div></li><li><span>02</span><div><h3>Char siu-style pork</h3><p>Sliced, seasoned pork commonly supplies the savory center of the bowl. Preparation and sweetness vary.</p></div></li><li><span>03</span><div><h3>Herbs and bean sprouts</h3><p>Fresh greens and sprouts add fragrance, coolness and crunch rather than serving only as decoration.</p></div></li><li><span>04</span><div><h3>Crisp rice elements</h3><p>Crackers or fried noodle pieces provide the crisp contrast that helps define the eating experience.</p></div></li><li><span>05</span><div><h3>Concentrated sauce</h3><p>A small amount gathers at the bottom and coats the noodles when the bowl is mixed.</p></div></li></ol></div></section>

    <section className="cao-method section"><div><p className="eyebrow">Traditional method, careful wording</p><h2>What Makes Cao Lau Noodles Different?</h2><p>Local and official tourism accounts repeatedly describe rice being treated with alkaline ash water before the noodles are steamed and cut. This alkaline treatment is commonly linked with the noodle&apos;s firm texture and muted yellow-brown color.</p><p>Published descriptions differ on the rice, ash source and exact process. Those differences matter: the safest conclusion is that alkaline treatment is a repeated traditional account, not that every modern producer follows one identical formula.</p></div><CaoLauImage src={images.ingredients} alt="Temporary editorial illustration of local noodles, rice paper, herbs and condiments" /></section>

    <section className="cao-history section"><div><p className="eyebrow">Fact vs tradition</p><h2>The Ba Le Well Story</h2></div><div><p>Ba Le well is a documented old well in Hoi An and official local heritage material strongly associates its water with traditional cao lau production. The link is an important part of how the dish is explained locally.</p><p>What cannot be established from the bowl is whether a particular noodle producer or restaurant used that water. Even Vietnam Tourism notes that strict “purist” practice is unlikely to be universal today. HAL therefore treats Ba Le water as a verified cultural association and traditional claim—not a test that decides whether every modern bowl is genuine.</p></div></section>

    <section className="cao-history section"><div><p className="eyebrow">History without a neat myth</p><h2>Did Cao Lau Come From Japan or China?</h2></div><div><p>Hoi An&apos;s role as an international trading port from the 15th to 19th centuries is well documented by UNESCO. Its architecture and culture reflect local and foreign influences, including Chinese, Japanese and later European connections.</p><p>That context makes cross-cultural influence plausible, but it does not prove one specific origin for cao lau. Tourism accounts variously point to Japanese noodles, Chinese-style pork or local invention. The more honest answer is that the dish&apos;s exact origin remains debated.</p><p>Enjoy the stories as part of Hoi An&apos;s food culture, but be cautious when one explanation is presented as settled historical fact.</p></div></section>

    <section className="cao-compare section" id="cao-lau-vs-mi-quang"><div><p className="eyebrow">Avoid ordering by name alone</p><h2>Cao Lau vs Mi Quang</h2><p>Both belong to Central Vietnam and can use relatively little liquid, but they are not interchangeable.</p></div><div className="cao-compare-scroll" role="region" aria-label="Cao lau and Mi Quang comparison" tabIndex={0}><table><thead><tr><th>Feature</th><th>Cao lau</th><th>Mi Quang</th></tr></thead><tbody><tr><th scope="row">Strongest association</th><td>Hoi An</td><td>Quang Nam–Da Nang region</td></tr><tr><th scope="row">Noodle</th><td>Thick, firm and chewy</td><td>Broad rice noodle, often white or yellow</td></tr><tr><th scope="row">Liquid</th><td>A little concentrated sauce</td><td>Small amount of seasoned broth, usually not enough to fill the bowl</td></tr><tr><th scope="row">Common protein</th><td>Char siu-style pork</td><td>May include pork, chicken, shrimp, fish or combinations</td></tr><tr><th scope="row">Finishing elements</th><td>Herbs, sprouts and crisp rice pieces</td><td>Herbs, peanuts and rice cracker are common</td></tr><tr><th scope="row">Defining impression</th><td>Chew and concentrated coating</td><td>Broader variation in broth and toppings</td></tr></tbody></table></div><p className="cao-note">Recipes vary by cook. This comparison is a decision aid, not a universal recipe standard.</p></section>

    <section className="cao-eating section"><CaoLauImage src={images.mixed} alt="Temporary editorial illustration of coated cao lau-style noodles being lifted after the bowl is mixed" /><div><p className="eyebrow">The first bite</p><h2>How Do You Eat Cao Lau?</h2><ol><li><strong>Look at the bowl first.</strong> Notice that the sauce sits underneath rather than filling it.</li><li><strong>Mix from the bottom.</strong> Turn the noodles gently so the concentrated sauce coats them and the herbs move through the bowl.</li><li><strong>Build a complete bite.</strong> Try noodle, pork, herbs and a crisp element together.</li><li><strong>Adjust carefully.</strong> Taste before adding chili or extra sauce; the balance differs by vendor.</li></ol><p>There is no need for ceremonial precision. Mixing simply allows the ingredients to work as one dish instead of five separate components.</p></div></section>

    <section className="cao-intro cao-worth section"><div><p className="eyebrow">The HAL view</p><h2>Is Cao Lau Worth Trying?</h2></div><div><p>Yes. For a first visit, it is one of the clearest ways to understand Hoi An through food. Its strong local association, unusual low-liquid structure and combination of chewy, soft, fresh and crisp textures make it meaningfully different from simply ordering another noodle soup.</p><p>That does not mean every traveler must love it or every bowl will be equally good. Try one thoughtful serving before turning the dish into a restaurant checklist.</p></div></section>

    <section className="cao-variation section"><div><p className="eyebrow">Variation is normal</p><h2>What to Look for in Your First Bowl</h2></div><div className="cao-signals"><article><h3>Firm, lively noodles</h3><p>They should offer resistance without feeling hard or dry.</p></article><article><h3>Enough sauce to coat</h3><p>The bowl should become integrated after mixing, not turn into soup.</p></article><article><h3>Fresh contrast</h3><p>Herbs and sprouts should brighten the pork and sauce.</p></article><article><h3>Real crunch</h3><p>Crisp pieces should still be crisp when the bowl arrives.</p></article></div><p>One vendor&apos;s sweeter pork or firmer noodle does not automatically make another version wrong. Freshness, texture and balance matter more than matching a single internet photograph.</p></section>

    <section className="cao-dietary section" id="dietary"><div><p className="eyebrow">Ask, do not assume</p><h2>Is Cao Lau Vegetarian or Gluten-Free?</h2></div><div><p>Traditional or common cao lau normally contains pork, and its sauce may include animal-derived cooking liquid. Vegetarian and vegan versions exist, but they are adaptations: removing visible pork does not establish that the sauce or stock is meat-free.</p><p>Although the noodles are generally rice-based, a bowl of cao lau should not automatically be treated as gluten-free. Marinades, soy sauce or other seasonings may contain wheat, and shared utensils, preparation surfaces, crisp components or oil can create cross-contact.</p><ul><li><strong>Coeliac disease or wheat allergy:</strong> ask about noodles, pork marinade, sauces, crisp elements and shared preparation. If communication is unclear, choose conservatively.</li><li><strong>Vegetarian or vegan:</strong> confirm the noodle, sauce, stock and toppings—not only the visible pork.</li><li><strong>Peanut, soy or other allergies:</strong> ask about garnishes, sauces and kitchen cross-contact rather than relying only on the menu name.</li></ul><p>HAL cannot verify individual kitchen practices. Discuss medical dietary needs directly with the restaurant or a knowledgeable guide.</p></div></section>

    <section className="cao-bridge section"><article><p className="eyebrow">Explore more Hoi An food</p><h2>See Cao Lau in Context</h2><p>Use the broader food guide to compare Hoi An&apos;s first-timer dishes, visit the market guide to understand ingredients, or fit meals into a short stay.</p><nav><Link className="secondary-button" href="/hoi-an-food-guide">Read the Hoi An Food Guide</Link><Link className="secondary-button" href="/banh-xeo-hoi-an">Compare With Banh Xeo</Link><Link className="secondary-button" href="/hoi-an-market-guide">Plan a Market Visit</Link><Link className="secondary-button" href="/3-days-in-hoi-an">Plan 3 Days in Hoi An</Link></nav></article><article><p className="eyebrow">Learn through cooking</p><h2>Want More Hands-On Context?</h2><p>A well-run cooking class can connect market ingredients and preparation techniques. Check the menu first: not every class teaches cao lau, and a short visitor class may simplify specialist noodle-making.</p><TrackedLink className="primary-button" href="/cooking-classes-hoi-an" sourcePage={sourcePage} destinationPage="/cooking-classes-hoi-an" section="cooking_bridge" ctaId="cao_lau_cooking_classes">Compare Hoi An Cooking Classes</TrackedLink></article></section>

    <section className="cao-sources section"><div><p className="eyebrow">How this guide was checked</p><h2>Sources &amp; Editorial Caution</h2></div><div><p>Place history was checked against <a href="https://whc.unesco.org/en/list/948/" target="_blank" rel="noopener noreferrer">UNESCO&apos;s Hoi An Ancient Town record</a>. Cao lau method and Ba Le context were compared across the <a href="https://www.hoianworldheritage.org.vn/en/news/Traditionnal-Hoi-An-food/something-in-the-local-water-makes-vietnam-s-cao-lau-noodles-special-558.hwh" target="_blank" rel="noopener noreferrer">Hoi An heritage portal</a>, its <a href="https://www.hoianworldheritage.org.vn/en/news/Monument/Ba-Le-Well-140.hwh" target="_blank" rel="noopener noreferrer">Ba Le well record</a>, <a href="https://danangfantasticity.com/en/cao-lau-hoi-an-a-traditional-noodle-specialty-of-hoi-an-vietnam" target="_blank" rel="noopener noreferrer">Da Nang tourism guidance</a> and <a href="https://www.vietnam.travel/things-to-do/4-must-try-dishes-in-hoi-an" target="_blank" rel="noopener noreferrer">Vietnam Tourism</a>. Mi Quang context was checked against the <a href="https://danangfantasticity.com/en/tinh-hoa-am-thuc-da-nang/mi-quang" target="_blank" rel="noopener noreferrer">Da Nang tourism portal</a>.</p><p>Where sources disagree or use legend-based language, HAL says so. Read more about our <Link href="/editorial-methodology">editorial methodology</Link>.</p></div></section>
  </main>;
}
