import Link from "next/link";
import { TrackedLink } from "@/components/tracked-link";
import { breadcrumbJsonLd } from "@/lib/jsonld";

const sourcePage = "hoi-an-market-guide";

const images = {
  hero: "/images/editorial/market-guide/hero.webp",
  herbs: "/images/editorial/market-guide/herbs-produce.webp",
  seafood: "/images/editorial/market-guide/seafood.webp",
  ingredients: "/images/editorial/market-guide/ingredients.webp",
  interaction: "/images/editorial/market-guide/interaction.webp",
} as const;

function MarketImage({ src, alt, priority = false }: { src: string; alt: string; priority?: boolean }) {
  return <figure className="market-visual"><img src={src} alt={alt} width="1200" height="800" loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"} decoding="async" /></figure>;
}

const ingredientLinks = [
  { name: "Vietnamese herbs", detail: "Herbs bring fragrance and contrast to cao lau, Mi Quang, banh xeo wraps and many family meals. The mix varies by cook and season." },
  { name: "Green papaya", detail: "Look for it shredded into crisp, tart salads or served as a fresh accompaniment. It may appear beside Hoi An chicken rice, but not every vendor uses it." },
  { name: "Banana blossom", detail: "Finely sliced banana blossom adds crunch and a gently astringent note to salads and herb mixtures. Ask how a vendor plans to prepare it rather than assuming one fixed use." },
  { name: "Fresh turmeric", detail: "Turmeric contributes color and earthy flavor to Central Vietnamese cooking. It is often associated with Mi Quang and banh xeo batter, although recipes differ." },
  { name: "Rice paper", detail: "Fresh, dry and grilled rice papers serve different jobs: wrapping banh xeo, making rolls, or providing the crisp layer in banh dap." },
  { name: "Local noodles", detail: "Compare thick cao lau noodles with broader Mi Quang noodles and fine rice noodles. Their shape and texture help explain why these dishes eat so differently." },
  { name: "Fish sauce & fermented condiments", detail: "These are seasonings and dipping-sauce foundations, not one interchangeable product. Flavor, intensity and ingredients vary, so travelers with allergies should ask specifically." },
  { name: "Seafood & vegetables", detail: "The fresh food areas show the everyday building blocks of local meals. Availability changes with supply, season and the time of day." },
];

export function HoiAnMarketGuidePage() {
  const breadcrumb = breadcrumbJsonLd([
    { name: "Home", url: "https://hoianlocaldays.com" },
    { name: "Things to Do in Hoi An", url: "https://hoianlocaldays.com/things-to-do-in-hoi-an" },
    { name: "Hoi An Market Guide", url: "https://hoianlocaldays.com/hoi-an-market-guide" },
  ]);

  return <main className="market-guide-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
    <div className="breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/things-to-do-in-hoi-an">Things to Do</Link><span>›</span><span>Market Guide</span></div>

    <section className="market-guide-hero section">
      <div><p className="eyebrow">A purposeful first visit · Reviewed August 2026</p><h1>Hoi An Market Guide: When to Go, What to See &amp; Local Tips</h1><p>Hoi An Market makes more sense when you treat it as a working food market, not a backdrop. Go with a few ingredients in mind and the stalls begin to explain the dishes you will eat around town.</p><nav className="quick-nav" aria-label="On this page"><a href="#quick-answer">Quick answer</a><a href="#when-to-go">When to go</a><a href="#ingredients">Ingredients</a><a href="#guided-visit">Guided visit</a></nav></div>
      <MarketImage src={images.hero} alt="Editorial illustration of a working morning food market with produce and seafood stalls" priority />
    </section>

    <section className="market-quick section" id="quick-answer"><div><p className="eyebrow">Quick answer</p><h2>Plan a Short Visit With a Clear Purpose</h2></div><dl><div><dt>Best time</dt><dd>06:00–08:00 for the strongest everyday food-market activity, based on current local observation.</dd></div><div><dt>Easier compromise</dt><dd>07:30–09:00 if you do not want a very early start.</dd></div><div><dt>How long</dt><dd>Allow about 30–60 minutes to look carefully without blocking working aisles.</dd></div><div><dt>Best for</dt><dd>Food-curious first-time visitors who want context before choosing dishes or a cooking class.</dd></div><div><dt>Do not miss</dt><dd>Fresh herbs, noodles, green papaya, banana blossom, turmeric, seafood and condiments.</dd></div></dl></section>

    <section className="market-intro section"><div><p className="eyebrow">The place</p><h2>What Is Hoi An Market?</h2></div><div><p>Hoi An Market is the traditional market on Tran Phu Street near the Bach Dang riverside area in the Ancient Town. Official tourism descriptions group its stalls around produce, spices, seafood, dried goods, household items, clothing and souvenirs.</p><p>For this guide, “Hoi An Market” means that central working market—not the evening visitor experience commonly called the night market. The morning food areas and the night market serve different purposes.</p><p>The useful mindset is simple: vendors are buying, selling, preparing and moving food for the day. Observe the system around you rather than expecting every aisle to perform for visitors.</p><p className="market-sources">Place and market composition checked against the <a href="https://danangfantasticity.com/en/hoi-an-market" target="_blank" rel="noopener noreferrer">Da Nang City Tourism Information Portal</a>.</p></div></section>

    <section className="market-timing section" id="when-to-go"><div><p className="eyebrow">Timing changes the character</p><h2>Best Time to Visit Hoi An Market</h2><p>The windows below are planning guidance from current local observation, not fixed hours for every stall.</p></div><div className="market-time-grid"><article><span>06:00–08:00</span><h3>Best for food-market activity</h3><p>Fresh produce, meat, fish and seafood movement is generally most interesting. It is also cooler for walking.</p></article><article><span>07:30–09:00</span><h3>Best compromise</h3><p>A practical choice for most travelers who want morning activity without the earliest start.</p></article><article><span>Late morning</span><h3>A changing rhythm</h3><p>Some early trade has eased and the weather can feel hotter. The market is not “finished,” but you see a different stage of the day.</p></article><article><span>Afternoon</span><h3>A different experience</h3><p>Expect a different product mix and pace. Go if it fits your route, but do not expect the same morning food-trade energy.</p></article></div></section>

    <section className="market-look section"><MarketImage src={images.herbs} alt="Editorial illustration of herbs, green papaya, banana blossom and fresh turmeric at a produce stall" /><div><p className="eyebrow">Look with purpose</p><h2>What to Look for Inside the Market</h2><p>Many visitors cross the market quickly, photograph the color and leave. Slow down just enough to notice how a working aisle is organized.</p><ul><li><strong>Produce:</strong> compare bundles of herbs, leafy greens and vegetables instead of treating them as one generic garnish.</li><li><strong>Noodles and rice paper:</strong> notice differences in width, thickness, freshness and intended use.</li><li><strong>Seafood:</strong> watch how fish, shrimp and shellfish are sorted and sold without obstructing the stall.</li><li><strong>Condiments:</strong> fish sauces and fermented products vary in strength and purpose; ask rather than guessing.</li><li><strong>Selection:</strong> weighing, trimming and checking ingredients reveal more about daily cooking than a staged photograph.</li></ul></div></section>

    <section className="market-ingredients section" id="ingredients"><div className="market-heading"><p className="eyebrow">Ingredient → dish</p><h2>Ingredients That Explain Hoi An Food</h2><p>The links below are common and useful, not universal recipe rules.</p></div><MarketImage src={images.ingredients} alt="Editorial illustration of noodles, rice paper, herbs and unlabeled condiments" /><div className="market-ingredient-list">{ingredientLinks.map((item, index) => <article key={item.name}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.name}</h3><p>{item.detail}</p></div></article>)}</div><p className="market-source-note">Official Vietnam Tourism material describes cao lau with thick noodles, pork, bean sprouts and fresh herbs, while its banh xeo guidance shows the pancake wrapped with rice paper and greens. Tra Que references connect local herbs and vegetables with dishes including cao lau, Mi Quang and banh xeo; that does not prove every market bundle came from Tra Que.</p></section>

    <section className="market-missed section"><div><p className="eyebrow">What visitors often miss</p><h2>Do More Than Photograph the Color</h2></div><div><p>A purposeful visit asks small questions: Which herb will be eaten raw? Which noodle belongs to which bowl? Is the banana blossom destined for a salad? How will the turmeric be used?</p><p>You do not need to interrogate a busy vendor. A guide, cook or willing seller can sometimes name an ingredient and connect it to a dish; otherwise, note it and look it up later. The goal is understanding, not turning work into a demonstration.</p><aside><strong>A good market visit changes the next meal.</strong> When you recognize an herb, wrapper or noodle on the plate, the market has added useful context.</aside></div></section>

    <section className="market-etiquette-section section"><MarketImage src={images.interaction} alt="Editorial illustration of a vendor handing fresh herbs to a customer" /><div><p className="eyebrow">Respect the workplace</p><h2>How to Visit Respectfully</h2><ul><li>Ask before photographing a vendor closely.</li><li>Avoid blocking narrow aisles, displays or active transactions.</li><li>Ask before touching or squeezing produce.</li><li>Bargaining may occur, but do not bargain aggressively over tiny amounts for entertainment.</li><li>Remember that vendors are working, not performing for tourists.</li><li>A greeting, smile or simple “xin chào” can make an interaction easier.</li></ul><p>Permission is especially useful when a person would be recognizable in your photograph. A wide market scene is different from placing a camera close to someone&apos;s face or hands.</p></div></section>

    <section className="market-safety section"><div><p className="eyebrow">Reduce risk, never promise safety</p><h2>Is Street Food at Hoi An Market Safe?</h2></div><div><p className="market-rule">Choose a busy stall, watch it being cooked, and eat it piping hot.</p><p>Fast turnover can be a useful signal, but it is not proof that a stall is safe. Also look for food cooked thoroughly and served hot, separation between raw and cooked ingredients, clean handling and sensible hot or cold holding.</p><p>Raw herbs and garnishes require more judgment because visual inspection cannot confirm water quality or handling. Travelers with allergies or coeliac disease should ask specifically about ingredients, sauces, shared utensils, oil and cross-contact. If communication is unclear, choose conservatively.</p><p className="market-sources">Public-health basis: <a href="https://www.who.int/docs/default-source/wpro---documents/posters/food-safety/guide-safe-food-for-travellers.pdf?sfvrsn=6d0d3448_2" target="_blank" rel="noopener noreferrer">WHO Guide on Safe Food for Travellers</a> and the <a href="https://www.cdc.gov/yellow-book/hcp/preparing-international-travelers/food-and-water-precautions-for-travelers.html" target="_blank" rel="noopener noreferrer">CDC Yellow Book</a>.</p></div></section>

    <section className="market-guided section" id="guided-visit"><MarketImage src={images.seafood} alt="Editorial illustration of a working seafood stall with fish, shrimp and shellfish" /><div><p className="eyebrow">Decision support</p><h2>Do You Need a Guided Market Tour?</h2><p><strong>A guide adds value</strong> when you can see and smell herbs, identify unfamiliar produce, learn how ingredients are selected and connect them to dishes you will cook or eat.</p><p><strong>A visit becomes superficial</strong> when the group only walks through while one person lectures, with little opportunity to observe ingredients or understand their use.</p><p>You can visit independently if you are comfortable observing respectfully and researching ingredients afterward. Choose a guided visit when translation, ingredient selection and dish context matter more than simply seeing the building.</p></div></section>

    <section className="market-bridges section"><article><p className="eyebrow">From stall to plate</p><h2>Combine the Market With Hoi An Food</h2><p>Use the market to understand ingredients, then use our food guide to decide which dishes deserve your limited meal time.</p><Link className="secondary-button" href="/hoi-an-food-guide">Read the Hoi An Food Guide</Link></article><article><p className="eyebrow">Hands-on context</p><h2>Market Visit + Cooking Class</h2><p>A cooking class is useful when the market visit feeds directly into ingredient choice, preparation and tasting—not when the market is only an itinerary checkbox.</p><TrackedLink className="primary-button" href="/cooking-classes-hoi-an" sourcePage={sourcePage} destinationPage="/cooking-classes-hoi-an" section="cooking_bridge" ctaId="market_cooking_classes">Compare Hoi An Cooking Classes</TrackedLink></article></section>

    <section className="market-checklist section"><div><p className="eyebrow">Before you go</p><h2>Practical Market Checklist</h2></div><ol><li><span>01</span><p>Choose morning if food-market activity is your priority.</p></li><li><span>02</span><p>Carry small notes if you expect to buy food or produce.</p></li><li><span>03</span><p>Wear shoes that handle wet or uneven market floors.</p></li><li><span>04</span><p>Keep your camera and body out of working lanes.</p></li><li><span>05</span><p>Pick three ingredients to recognize before you arrive.</p></li><li><span>06</span><p>Use the visit to inform your next dish, class or itinerary decision.</p></li></ol><nav aria-label="Continue planning"><Link href="/things-to-do-in-hoi-an">Explore Things to Do</Link><Link href="/3-days-in-hoi-an">Fit the Market Into 3 Days</Link><Link href="/editorial-methodology">How HAL Checks Local Guidance</Link></nav></section>
  </main>;
}
