import Link from "next/link";
import { getExperience } from "@/data/experiences";
import type { LandingPage as PageData } from "@/data/pages";
import { breadcrumbJsonLd } from "@/lib/jsonld";
import { AffiliateDisclosure, ExperienceCard } from "./experience-card";

export function LandingPage({ page }: { page: PageData }) {
  const items = page.experienceIds.map(getExperience).filter(Boolean);
  const jsonLd = breadcrumbJsonLd([{ name: "Home", url: "https://hoianlocaldays.com" }, { name: page.title, url: `https://hoianlocaldays.com/${page.slug}` }]);
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><div className="breadcrumb"><Link href="/">Home</Link><span>›</span><span>{page.title}</span></div><section className="landing-hero section"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.description}</p><AffiliateDisclosure /><nav className="quick-nav" aria-label="On this page"><a href="#quick-picks">Quick picks</a><a href="#how-to-choose">How to choose</a><a href="#related">Related guides</a></nav></section><section className="quick-picks section" id="quick-picks"><div className="section-heading"><p className="eyebrow">Quick picks</p><h2>{items.length ? "Compare the best fit" : "Ready for verified partners"}</h2><p>{page.intro}</p></div>{items.length ? <div className="experience-grid">{items.map((item, index) => <ExperienceCard key={item!.id} experience={item!} page={page.slug} position="quick-pick" label={index === 0 ? "Best starting point" : index === 1 ? "Good alternative" : undefined} />)}</div> : <div className="empty-state"><strong>No invented offers here.</strong><p>Provider names, live pricing and affiliate links will appear only after verified partner data is supplied.</p></div>}</section><section className="choose-section section" id="how-to-choose"><div><p className="eyebrow">How to choose</p><h2>Use the day well</h2></div><div className="decision-list"><article><span>01</span><h3>Start with pace</h3><p>A half-day leaves room for the old town, pool or beach. Full-day trips make sense when the destination is the priority.</p></article><article><span>02</span><h3>Check the practical fit</h3><p>Confirm pickup, children’s policy, dietary needs and mobility before comparing small price differences.</p></article><article><span>03</span><h3>Book through a trusted provider</h3><p>When partner links are connected, compare cancellation terms and what is included before leaving this page.</p></article></div></section><section className="related section" id="related"><p className="eyebrow">Continue planning</p><h2>Related Hoi An guides</h2><div>{page.guideLinks.map((link) => <Link key={link.href} href={link.href}>{link.label}<span>→</span></Link>)}</div></section></main>;
}
