import Link from "next/link";
import { TrackedLink } from "./tracked-link";
import { EditorSignal } from "./editor-signal";
import { AffiliateDisclosure } from "./affiliate-disclosure";
import { CookingComparisonCard, QuickPicks } from "./cooking-editorial";
import { breadcrumbJsonLd } from "@/lib/jsonld";
import { commonMySonMistakes, groupVsPrivate, morningVsAfternoon, mySonExperiences, mySonOverview, mySonQuickPicks, visitStyles } from "@/data/my-son";

const page = "my-son-tours-from-hoi-an";

export function MySonPage() {
  const breadcrumb = breadcrumbJsonLd([
    { name: "Home", url: "https://hoianlocaldays.com" },
    { name: "Things to Do in Hoi An", url: "https://hoianlocaldays.com/things-to-do-in-hoi-an" },
    { name: "My Son Sanctuary from Hoi An", url: "https://hoianlocaldays.com/my-son-tours-from-hoi-an" },
  ]);
  return <main className="my-son-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
    <div className="breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/things-to-do-in-hoi-an">Things to Do</Link><span>›</span><span>My Son Sanctuary</span></div>

    <section className="my-son-hero section"><p className="eyebrow">Cultural trip from Hoi An</p><h1>My Son Sanctuary from Hoi An: How to Choose the Right Trip</h1><p>A practical guide to visiting My Son from Hoi An — including morning vs afternoon, group vs private trips, transport options and who the experience suits best.</p><EditorSignal /><div className="hero-actions"><a className="primary-button" href="#choose-your-visit">Find Your Best Way to Visit</a><Link className="secondary-button" href="/3-days-in-hoi-an">See a 3-Day Hoi An Itinerary</Link></div></section>

    <section className="my-son-answer section"><div><p className="eyebrow">The quick answer</p><h2>Is My Son Worth Visiting From Hoi An?</h2></div><div><p><strong>It can be a very worthwhile addition</strong> for travelers interested in history, architecture, archaeology, Cham heritage and cultural sites beyond Hoi An Ancient Town.</p><p>It may be less compelling if your time is very limited and your priorities are mainly food, beaches or hands-on activities. My Son is an option with a clear cultural focus—not a stop every visitor must make.</p></div></section>

    <section className="my-son-context section"><div><p className="eyebrow">Concise context</p><h2>What Is My Son Sanctuary?</h2></div><div><p>My Son is a UNESCO World Heritage Site associated with the Champa civilization. The sanctuary contains Hindu temple structures whose historical development spans roughly the 4th to 13th centuries. It sits outside Hoi An, so every visit requires a transport decision as well as a choice about how much interpretation you want.</p><Link className="context-link" href="/my-son-sanctuary-guide">Read the informational My Son Sanctuary guide →</Link></div></section>

    <section className="my-son-styles section" id="choose-your-visit"><div className="my-son-heading"><p className="eyebrow">Main decision</p><h2>Which My Son Experience Is Right for You?</h2><p>Choose the experience format first. Bookable providers can be compared later without treating each OTA listing as a different underlying experience.</p></div><div className="my-son-style-grid">{visitStyles.map((style, index) => <article key={style.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{style.title}</h3><strong>Best for</strong><ul>{style.bestFor.map((item) => <li key={item}>{item}</li>)}</ul><p><b>Trade-off:</b> {style.tradeOff}</p></article>)}</div></section>

    <section className="my-son-picks section" id="quick-picks"><div className="section-heading"><p className="eyebrow">Quick picks</p><h2>Short on Time? Start Here</h2><p>Three distinct starting points: an organized group visit, an earlier departure or a private format.</p></div><AffiliateDisclosure /><QuickPicks experiences={mySonQuickPicks} page={page} /></section>

    <section className="my-son-comparison section"><div className="my-son-heading"><p className="eyebrow">Timing decision</p><h2>Morning or Afternoon?</h2><p>Neither is universally better. Match the departure window to your heat tolerance, energy and plans in Hoi An.</p></div><div className="my-son-compare-grid">{morningVsAfternoon.map((option) => <article key={option.title}><h3>{option.title}</h3><div><strong>Potential advantages</strong><ul>{option.advantages.map((item) => <li key={item}>{item}</li>)}</ul></div><div><strong>Potential disadvantages</strong><ul>{option.disadvantages.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div><p className="my-son-recommendation"><strong>HAL recommendation:</strong> Start earlier if heat and photography matter most. Choose the afternoon when protecting a relaxed Hoi An morning matters more, while keeping weather and a later return in mind.</p></section>

    <section className="my-son-split section"><div><p className="eyebrow">Format decision</p><h2>Group Tour or Private Trip?</h2></div><div className="my-son-compare-grid">{groupVsPrivate.map((option) => <article key={option.title}><h3>{option.title}</h3><strong>Choose this if</strong><ul>{option.chooseIf.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section className="my-son-guide section"><div><p className="eyebrow">Interpretation</p><h2>Do You Need a Guide at My Son?</h2></div><div><p>A guide can add meaningful context because much of the site’s significance comes from understanding Champa history, Hindu religious context, architecture and how the sanctuary developed.</p><p>An independent visit can still suit slower travelers, photographers and visitors who prefer self-guided exploration. A guide adds context; it is not mandatory for every visitor.</p></div></section>

    <section className="my-son-commerce section" id="compare-all"><div className="section-heading inverse"><p className="eyebrow">HAL editorial shortlist</p><h2>Compare Our 5 My Son Picks</h2><p>Compare five meaningfully different visit styles first, then use the available provider to check current details.</p></div><div className="editorial-comparison-list">{mySonExperiences.map((experience, index) => <div id={experience.id} key={experience.id}><CookingComparisonCard experience={experience} position={`comparison_${index + 1}`} page={page} /></div>)}</div></section>

    <section className="my-son-fit section"><div className="my-son-heading inverse"><p className="eyebrow">Traveler fit</p><h2>Who Is My Son Best For?</h2></div><div className="my-son-fit-grid"><article><h3>Strong fit</h3><ul>{mySonOverview.editorial.bestFor.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>Think Twice If</h3><ul>{mySonOverview.editorial.notIdealFor.map((item) => <li key={item}>{item}</li>)}</ul></article></div></section>

    <section className="my-son-family section"><div><p className="eyebrow">Family planning</p><h2>Visiting My Son With Kids</h2></div><div><p>The open-air setting, unusual architecture and cultural story can create an educational visit, particularly for some older children. It still needs realistic planning around heat, walking, travel time, attention span and breaks.</p><p>No age or comfort level is guaranteed; use what you know about your child rather than treating My Son as a universal family activity.</p><Link className="primary-button" href="/hoi-an-with-kids">Planning Hoi An With Kids</Link></div></section>

    <section className="my-son-alternatives section"><div className="my-son-heading"><p className="eyebrow">Choose the right priority</p><h2>My Son or Another Hoi An Experience?</h2></div><div className="my-son-alternative-grid"><article><h3>Choose My Son</h3><p>If history, architecture and culture matter most.</p></article><article><h3>Choose a Cooking Class</h3><p>If food and a hands-on activity matter most.</p><TrackedLink href="/cooking-classes-hoi-an" sourcePage="my-son-tours-from-hoi-an" destinationPage="/cooking-classes-hoi-an" section="alternatives" ctaId="myson_cooking">Compare cooking classes →</TrackedLink></article><article><h3>Choose Basket Boats</h3><p>If you want a shorter, lighter activity.</p><TrackedLink href="/basket-boat-hoi-an" sourcePage="my-son-tours-from-hoi-an" destinationPage="/basket-boat-hoi-an" section="alternatives" ctaId="myson_basket_boat">Compare basket boats →</TrackedLink></article><article><h3>Stay in Hoi An</h3><p>If time is limited and you have not explored Ancient Town yet.</p><Link href="/things-to-do-in-hoi-an">Explore things to do →</Link></article></div></section>

    <section className="my-son-itinerary section"><div><p className="eyebrow">Planning context</p><h2>Where My Son Fits Into a Hoi An Itinerary</h2></div><div><p>For a three-day stay, My Son works best as a cultural option when you have already protected time for Ancient Town and do not need to fit every signature activity into the same day. It is not a mandatory part of the plan.</p><Link className="primary-button" href="/3-days-in-hoi-an">See Our 3-Day Hoi An Itinerary</Link></div></section>

    <section className="my-son-mistakes section"><div className="my-son-heading inverse"><p className="eyebrow">Before choosing</p><h2>Common Mistakes When Choosing a My Son Trip</h2></div><div className="my-son-mistake-list">{commonMySonMistakes.map((mistake, index) => <article key={mistake.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{mistake.title}</h3><p>{mistake.body}</p></div></article>)}</div></section>

    <section className="my-son-trust section"><div><p className="eyebrow">Editorial note</p><h2>Experience First, Provider Second</h2></div><div><p>Recommendations are based on traveler fit and current, verified information where it is available. Hoi An Local Days does not claim that these My Son experiences have been personally tested.</p><p>The five picks represent different visit styles. Their Viator or GetYourGuide links are booking options, not the reason an experience is recommended. If your time is limited or culture is not a priority, staying in Hoi An may be the better choice.</p><Link href="/editorial-methodology">Read our editorial methodology →</Link></div></section>
  </main>;
}
