import Link from "next/link";
import { TrackedLink } from "@/components/tracked-link";
import { breadcrumbJsonLd } from "@/lib/jsonld";
import { experienceFormats, interestCategories, thingsToDoQuickPicks, timeAvailable, travelerTypes } from "@/data/things-to-do";

const commercialCtaIds: Record<string, string> = {
  "/cooking-classes-hoi-an": "things_cooking",
  "/basket-boat-hoi-an": "things_basket_boat",
  "/my-son-tours-from-hoi-an": "things_myson",
};

export function ThingsToDoHub() {
  const breadcrumb = breadcrumbJsonLd([{ name: "Home", url: "https://hoianlocaldays.com" }, { name: "Things to Do in Hoi An", url: "https://hoianlocaldays.com/things-to-do-in-hoi-an" }]);
  return <main className="things-hub"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><div className="breadcrumb"><Link href="/">Home</Link><span>›</span><span>Things to Do</span></div>
    <section className="things-hero section"><p className="eyebrow">Hoi An Local Days discovery guide</p><h1>Best Things to Do in Hoi An</h1><p>A local guide to the experiences actually worth considering — from cooking and food to culture, beaches, family activities and day trips.</p><small>Start with what fits your trip, not the longest possible checklist.</small><div className="hero-actions"><a className="primary-button" href="#interests">Explore by Interest</a><a className="secondary-button" href="#top-picks">See Our Top Picks</a></div></section>
    <section className="things-picks section" id="top-picks"><div className="hub-heading"><p className="eyebrow">Quick picks</p><h2>Short on Time? Start With These</h2></div><div className="things-pick-list">{thingsToDoQuickPicks.map((item, index) => <article key={item.id}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.shortDescription}</p><small><strong>Best for:</strong> {item.bestFor}</small></div>{item.href ? <TrackedLink href={item.href} sourcePage="things-to-do-in-hoi-an" destinationPage={item.href} section="quick_picks" ctaId={commercialCtaIds[item.href]}>Explore <b>→</b></TrackedLink> : null}</article>)}</div></section>
    <section className="interest-section section" id="interests"><div className="hub-heading inverse"><p className="eyebrow">Explore by interest</p><h2>Find What Fits Your Trip</h2></div><div className="interest-grid">{interestCategories.map((item) => { const content = <><h3>{item.title}</h3><p>{item.shortDescription}</p><ul>{item.examples?.map((example) => <li key={example}>{example}</li>)}</ul>{item.href && <b>Explore guide →</b>}</>; return item.href && commercialCtaIds[item.href] ? <TrackedLink href={item.href} key={item.id} sourcePage="things-to-do-in-hoi-an" destinationPage={item.href} section="interests" ctaId={commercialCtaIds[item.href]}>{content}</TrackedLink> : item.href ? <Link href={item.href} key={item.id}>{content}</Link> : <article key={item.id}>{content}</article>; })}</div></section>
    <section className="format-section section"><div className="hub-heading"><p className="eyebrow">Experience formats</p><h2>What Kind of Hoi An Experience Do You Want?</h2></div><div className="format-grid">{experienceFormats.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.guidance}</p><small>{item.examples.join(" · ")}</small></article>)}</div><aside className="hub-local-note"><strong>Planning a cultural trip?</strong><span>Understand My Son&apos;s Champa history, outdoor visit and interpretation needs before choosing transport or a tour.</span><Link href="/my-son-sanctuary-guide">Read the My Son Sanctuary guide →</Link></aside><aside className="hub-local-note"><strong>Planning a coconut-village visit?</strong><span>Understand Cam Thanh&apos;s busy and quiet areas, local cost references and optional extras before choosing a tour.</span><Link href="/cam-thanh-coconut-village">Read the Cam Thanh guide →</Link></aside><aside className="hub-local-note"><strong>Taking children on a basket boat?</strong><span>Check age policies, child-sized life jackets, spinning and route atmosphere before choosing.</span><Link href="/basket-boat-hoi-an-with-kids">Read the parent decision guide →</Link></aside></section>
    <section className="cooking-feature section"><div className="cooking-feature-art" aria-hidden="true"><span>Hands-on Hoi An</span></div><div><p className="eyebrow">One experience we’d start with</p><h2>A Cooking Class</h2><p>Cooking classes combine several parts of Hoi An in one half-day experience — local food, markets, hands-on activity and often the surrounding countryside.</p><p><Link className="context-link" href="/what-to-expect-hoi-an-cooking-class">Understand the class formats and what to check →</Link></p><p><Link className="context-link" href="/hoi-an-food-guide">First understand what to eat in Hoi An →</Link></p><p><Link className="context-link" href="/hoi-an-market-guide">Plan a purposeful visit to Hoi An Market →</Link></p><TrackedLink className="primary-button" href="/cooking-classes-hoi-an" sourcePage="things-to-do-in-hoi-an" destinationPage="/cooking-classes-hoi-an" section="featured_cooking" ctaId="things_cooking">Compare Hoi An Cooking Classes</TrackedLink></div></section>
    <section className="traveler-section section"><div className="hub-heading"><p className="eyebrow">Choose by traveler type</p><h2>What’s Best for You?</h2></div><div className="traveler-grid">{travelerTypes.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.guidance}</p></article>)}</div></section>
    <section className="time-section section"><div><p className="eyebrow">Fit the real itinerary</p><h2>How Much Time Do You Have?</h2></div><div className="time-list">{timeAvailable.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.guidance}</p></article>)}</div></section>
    <section className="hub-itinerary section"><div><p className="eyebrow">Staying for a few days?</p><h2>Put the Experiences Into a Real Plan</h2></div><div><p>First choose how much time Hoi An deserves, then use our relaxed itinerary to balance the Ancient Town, one hands-on experience, countryside and time to slow down.</p><p><Link className="context-link" href="/hoi-an-old-town-guide">Understand what Hoi An Old Town is and how to visit →</Link></p><p><Link className="context-link" href="/how-many-days-in-hoi-an">Decide how many days you need →</Link></p><Link className="primary-button" href="/3-days-in-hoi-an">See the 3-Day Itinerary</Link></div></section>
    <section className="hub-trust section"><div><p className="eyebrow">Editorial approach</p><h2>How We Choose What to Recommend</h2></div><div><p>We focus on experiences that add something meaningful to a Hoi An trip. Instead of listing every available activity, we look at traveler fit, local character, distinctiveness, practical value and how easy the experience is to fit into a real itinerary.</p><p>Booking relationships do not determine what we recommend.</p></div></section>
  </main>;
}
